Acme\DemoBundle\Entity\Category:
  type: entity
  #repositoryClass: Doctrine\Tests\ORM\Mapping\CategoryRepository
  table: category
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
  manyToOne:
    users:
      targetEntity: Acme\DemoBundle\Entity\UserX
      joinColumn:
        name: user_id
        referencedColumnName: id