Acme\DemoBundle\Entity\User:
  type: entity
  #repositoryClass: Doctrine\Tests\ORM\Mapping\UserRepository
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
#  fields:
#    signedIn:
#      type: datetime
  oneToMany:
    categories:
      mappedBy: categories
      targetEntity: Acme\DemoBundle\Entity\Category
      joinColumn:
        name: category_id
        referencedColumnName: id